config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'sessions/new'

  root to: "rooms#home"
  get "rooms/home"
  get "rooms/:id/post", to: "rooms#post", as: :rooms_post
  namespace :admin do
    resources :users
    get "users/:id/profile", to: "users#profile", as: :users_profile
  end
  resources :rooms do
    collection do
      get "search"
    end
  end
  resources :reservations

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/session.rb
class Session
  include ActiveModel::Model
  attr_accessor :email, :password
  validates :email, presence: true
  validates :password, presence: true

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  validates :start_day, presence: true
  validates :end_day, presence: true
  validates :number_of_people, presence: true
  validate :end_day_not_before_start_day
  validate :start_day_not_before_today
  
  private
    def end_day_not_before_start_day
      if end_day && start_day
        errors.add(:end_day, 'は開始日より後の日付を選択して下さい') if end_day < start_day
      end
    end

    def start_day_not_before_today
      if start_day.present? && start_day < Date.yesterday
        errors.add(:start_day, 'は現在日より後の日付を選択して下さい')
      end
    end
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :photo
  has_many :reservations, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :introduction,
    presence: true,
    length: {maximum: 50}
  validates :adress, presence: true
  validates :price, presence: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :reservations
  has_secure_password
  has_one_attached :avatar

  validates :name,
    presence: true,
    length: {maximum: 20}
  validates :email,
    uniqueness: true,
    presence: true
  validates :introduction, length: {maximum: 50}
  validates :password, on: :create,
    presence: true,
    confirmation: true,
    length: {minimum: 6}
  validates :password, on: :update,
    confirmation: true,
    length: {minimum: 6}, if: Proc.new{|user| user.password.present?}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_q
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    avatar_path = Rails.root.join("app", "assets", "images", "default_icon.jpeg")
    file = File.open(avatar_path)
    @user.avatar.attach(io: file, filename: "default_icon.jpeg")

    if @user.save
      redirect_to rooms_home_path, notice: "User, #{@user.name} was registered."
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = @w.result
  end

  def update
    @user = User.find(params[:id])
    if @user&.authenticate(params.require(:user).permit(:current_password)[:current_password]) || params.require(:user).permit(:current_password)[:current_password] == current_user.password_digest
      if @user.update(user_params)
        redirect_to admin_user_path(@user), notice: "User #{@user.name} was updated."
      elsif params.require(:user).permit(:current_password)[:current_password] == current_user.password_digest
        render "profile"
      else
        render "edit"
      end
    else
      redirect_to edit_admin_user_path, alert: "現在のパスワードが一致しません。"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "User #{@user.name} was deleted."
  end

  def search
    @results = @q.result
  end

  def set_q
    @q = Room.ransack(params[:q])
    @w = User.ransack(params[:w])
  end

  def profile
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :avatar, :admin,)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_avatar
    @avatar = current_user.avatar
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_q
  def new
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:start_day,:end_day,:number_of_people,:room_id,:user_id))
    if @reservation.save
      redirect_to rooms_home_path, notice: "room was successfuly reserved."
    else
      redirect_to room_path(@reservation.room_id), alert: @reservation.errors.full_messages
    end
  end

  def edit
  end

  def show
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path, notice: "reservation was deleted."
  end

  def index
    if current_user.admin
      @reservation = Reservation.all
    else
      @reservation = current_user.reservations
    end
  end

  def search
    @results = @q.result
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_home_path, notice: "room was successfuly created."
    else
      render "new"
    end
  end

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new

    gon.start_day = Reservation.where(room_id: params[:id]).pluck(:start_day)
    gon.end_day = Reservation.where(room_id: params[:id]).pluck(:end_day)
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room =Room.find(params[:id])
    if @room.update(room_params)
      redirect_to rooms_post_path(current_user.id), notice: "Room #{@room.name} was successfuly updated."
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_home_path, notice: "Room #{@room.name} was deleted."
  end

  def home
    @results = @q.result
  end

  def search
    @results = @q.result
  end

  def post
    if current_user.admin
      @rooms = Room.all
    else
      @rooms = current_user.rooms
    end
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

  private
    def room_params
      params.require(:room).permit(:name,:introduction,:price,:adress,:photo,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_q
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "#{user.name} was logged in"
    else
      redirect_to sessions_new_path, alert: "Invalid email or password"
    end
  end

  def destroy
    reset_session
    redirect_to rooms_home_path, notice: "logged out"
  end

  def search
    @results = @q.result
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/edit.html.slim
= stylesheet_link_tag 'common','admin/user_edit'
.wrapper
  .edit_account
    p アカウント編集
    = form_with model: [:admin, @user], local: true do |f|
      = render 'shared/error', model: f.object
      -if alert
        .alert
          ul
           li = alert
      .form_group
        = f.label :email, "メールアドレス"
        br
        = f.text_field :email, placeholder: "#{@user.email}", id: "account_form"
      .form_group
        = f.label :password, "変更後パスワード（変更する場合のみ記入）"
        br
        = f.password_field :password, placeholder: nil,id: "account_form"
      .form_group
        = f.label :password_confirmation, "パスワード確認用（変更する場合のみ記入）"
        br
        = f.password_field :password_confirmation, placeholder: nil, id: "account_form"
      .form_group
        = f.label :current_password, "現在のパスワード"
        br
        = f.password_field :current_password, placeholder: "現在のパスワードを入力", id: "account_form"
      .form_group
        = f.submit "更新", class: "update", id: "account_form"

      = link_to admin_user_path, id: "back_page" do
        .back
          | 戻る
    .push

app/views/admin/users/index.html.slim
= stylesheet_link_tag 'common','admin/user_index'
.notice
    = flash[:notice]
.result_sort
  .result
    p ユーザー人数：#{@users.count}人
  .sort
.wrapper
  .search
    -@users.each do |user|
      .search_users
        = link_to admin_users_profile_path(user)
          .users_avatar
            -if user.avatar.attached?
              = image_tag user.avatar.variant(resize_to_fill: [70,70]), class: 'avatar'
          .users_information
            .users_name = "ユーザー名：#{user.name}"
            .users_introduction
              | 自己紹介
              br
              = user.introduction
            .users_rooms
              | 登録ルーム数：#{user.rooms.count}件
            = link_to admin_user_path(user.id), method: :delete, data:{confirm: "ユーザーを削除してもよろしいでしょうか？"}, class: "delete_user" do
              .delete
                p 削除

app/views/admin/users/new.html.slim
= stylesheet_link_tag 'common','admin/user_new'
.wrapper
  .create_account
    p 新しいアカウントを作成
    = form_with model: [:admin, @user], local: true do |f|
      = render 'shared/error', model: f.object
      .form-group
        = f.text_field :name, placeholder: "ユーザー名", class: "form-control"
      .form-group
        = f.text_field :email, placeholder: "メールアドレス", class: "form-control"
      .form-group
        = f.password_field :password, placeholder: "パスワード", class: "form-control"
      .form-group
        = f.password_field :password_confirmation, placeholder: "パスワード（確認）", class: "form-control"
      .form-check
        = f.label :admin, class: "form-check-label" do
          = f.check_box :admin, class: "form-check-input"
          | 管理者権限
      .form-submit
        = f.submit "新しいアカウントを作成", class: "submit"
    .login
      = link_to "既にアカウントをお持ちの方はログイン", login_path, class: "link_login"

app/views/admin/users/profile.html.slim
= stylesheet_link_tag 'common','admin/user_show','admin/profile'
.user_information
  .side_bar
    .content
      .menu_acount
        = link_to "アカウント", admin_user_path, id: "menu_text"
      br
      .menu_profile
        = link_to "プロフィール", admin_users_profile_path, id: "menu_text"
  .account
    p プロフィール
    .profile
      = form_with model: [:admin, @user], local: true do |f|
        = render 'shared/error', model: f.object
        .avatar
          -if @user.avatar.attached?
            = image_tag @user.avatar.variant(resize_to_fill: [70,70]), id: "user_icon"
        table
          tr
            th = f.label :avatar, "アイコン画像"
            td = f.file_field :avatar
          tr
            th = f.label :name, "名前"
            td = f.text_field :name, placeholder: "#{@user.name}", class: "name"
          tr
            th = f.label :introduction, "自己紹介"
            td = f.text_area :introduction, placeholder: "#{@user.introduction}", class: "introduction"
            = f.hidden_field :current_password, value: @user.password_digest
        -if session[:user_id] == @user.id
          .edit_account
            = f.submit "更新", class: "update"

app/views/admin/users/show.html.slim
= stylesheet_link_tag 'common','admin/user_show'
.notice
    = flash[:notice]
.user_information
  .side_bar
    .content
      .menu_account
        = link_to "アカウント", admin_user_path, id: "menu_text"
      br
      .menu_profile
        = link_to "プロフィール", admin_users_profile_path, id: "menu_text"
  .account
    p アカウント
    .mail_password
      table
        tr
          th メールアドレス
          td = @user.email
        tr
          th パスワード
          td &#042;&#042;&#042;&#042;&#042;&#042;&#042;&#042;&#042;
      -if session[:user_id] == @user.id
        .edit_account
          = button_to "編集", {controller: "admin/users", action: "edit"}, {method: :get, id: "button"}

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Poteshare
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'common', 'data-turbolinks-track': 'reload'
    script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css"
    script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"
  header
    .header_search
      .poteshare
        .to_home
          = link_to 'Pote Share', rooms_home_path, id: "to_home"
        .search_room_forms
          = render partial: "shared/searchform",locals: {q: @q}
      .user_avatar
        -if current_user
          = current_user.name
          .current_user_avatar
            .user_icon
              = image_tag current_user.avatar.variant(resize_to_fill: [50,50]), id: "user_icon"
        -else
          = link_to login_path, id: "header_login" do
            .header_login
              | ログイン
          = link_to new_admin_user_path, id: "header_login"  do
            .header_create_account
              | 登録する
      .menu
        .menu_content
          = render partial: "shared/menu"
  body
    == yield
  footer
    | &copy 2020 POTEPAN.INC.

app/views/reservations/edit.html.slim
h1 Reservations#edit
p Find me in app/views/reservations/edit.html.slim

app/views/reservations/index.html.slim
= stylesheet_link_tag 'common','reservations_index'
.notice
  = flash[:notice]
.wrapper
  p 予約済みルーム一覧
  .rserved_room
    table
      thead
        tr
          th ルーム画像
          th ルーム名
          th ルーム紹介
          th 合計料金
          th 開始日
          th 終了日
          th 予約確定日時
          th
      tbody
        -@reservation.each do |reservation|
          tr
            td = link_to room_path(reservation.room_id)
              = image_tag reservation.room.photo.variant(resize_to_fill: [250,150])
            td.room_name = link_to "#{reservation.room.name}", room_path(reservation.room_id), id: "reserved_room_name"
            td = reservation.room.introduction
            td = (reservation.room.price * reservation.number_of_people).to_s(:delimited, delimiter: ",") + "円"
            td = l reservation.start_day, format: :short
            td = l reservation.end_day, format: :short
            td = l reservation.created_at, format: :default
            td = link_to reservation_path(reservation.id), method: :delete, data:{confirm: "予約を削除してもよろしいでしょうか？"}, class: "delete_reservation" do
              .delete
                p 削除

app/views/reservations/new.html.slim
= stylesheet_link_tag 'common','show'
.show_room
  .show_photo_reservation
    -if @room(:id).photo.attached?
      = image_tag @room.photo.variant(resize_to_fill: [700,400])
    .room_information
      .avatar avatar
      .name_adress
        #name = @room.name
        br
        = @room.adress
    .introduction = @room.introduction
  .reservation_form
    .price = @room.price.to_s(:delimited, delimiter: ",") + "円 / 日"
    .form = form_with model: @reservation, local: true do |f|
      = f.label :start_day, "開始日"
      br
      = f.date_field :start_day, class: "input"
      br
      = f.label :end_day, "終了日"
      br
      = f.date_field :end_day, class: "input"
      br
      = f.label :number_of_people, "人数"
      br
      = f.number_field :number_of_peoplem, min: 0, class: "input"
      br
      = f.submit "予約する", class: "button"

app/views/reservations/show.html.slim
h1 Reservations#show
p Find me in app/views/reservations/show.html.slim

app/views/rooms/edit.html.slim
= stylesheet_link_tag 'common',"new"
.content
  .sidebar
    p 基本情報
  .room_information
    p ルーム情報編集
    = form_with model: @room, local: true do |f|
      = render 'shared/error', model: f.object
      table
        tr
          th
            = f.label :name, 'ルーム名'
            .neccesary 必須
          td
            = f.text_field :name, placeholder: 'ルーム名を入力', class: 'input'
        tr
          th
            = f.label :introduction, 'ルーム紹介'
            .neccesary 必須
          td
            = f.text_area :introduction, placeholder: 'ルーム説明を入力', class: 'input_area'
        tr
          th
            = f.label :price, '料金'
            .neccesary 必須
          td
            = f.text_field :price, placeholder: '1日あたり料金を入力', class: 'input'
        tr
          th
            = f.label :adress, '住所'
            .neccesary 必須
          td
            = f.text_field :adress, placeholder: '住所を入力', class: 'input'
        tr
          th
            = f.label :photo, 'ルーム画像'
            .neccesary 必須
          td
            = f.file_field :photo
            = f.hidden_field :user_id, value:current_user.id
        tr
          th
            = f.submit '更新', class: 'button'

app/views/rooms/home.html.slim
= stylesheet_link_tag 'home','common'
body
  .notice
    = flash[:notice]
  .search
    p Potepan Shareでまだ体験したことのない旅をしよう
    | エリア
    .search_area
      = search_form_for @q, url: search_rooms_path do |f|
        = f.search_field :adress_cont, placeholder: "東京", class: "search_area"
        = f.submit "探す", class: "button"
  .push
  .recommend_place
    p おすすめのエリア
    .recommended_four_places
      .tokyo
        = link_to search_rooms_path q: {adress_cont: "東京"}
          = image_tag "img_tokyo.jpeg", class: "photo"
          p 東京
      .osaka
        = link_to search_rooms_path q: {adress_cont: "大阪"}
          = image_tag "img_osaka.jpeg", class: "photo"
          p 大阪
      .kyoto
        = link_to search_rooms_path q: {adress_cont: "京都"}
          = image_tag "img_kyoto.jpeg", class: "photo"
          p 京都
      .sapporo
        = link_to search_rooms_path q: {adress_cont: "札幌"}
          = image_tag "img_sapporo.jpeg", class: "photo"
          p 札幌

app/views/rooms/index.html.slim
= stylesheet_link_tag 'common','index'
p 検索結果： 件
.wrapper
  = link_to room_path(room) do
    .search
      -@rooms.each do |room|
        .search_rooms
          .room_photo
            -if room.photo.attached?
              = image_tag room.photo.variant(resize_to_fill: [300,180]), class: 'photo'
        .room_information
          .room_name = room.name
          .room_adress = room.adress
          .room_price = room.price.to_s(:delimited, delimiter: ",") + "円"

app/views/rooms/new.html.slim
= stylesheet_link_tag 'common',"new"
.content
  .sidebar
    p 基本情報
  .room_information
    p ルーム情報登録
    = form_with model: @room, local: true do |f|
      = render 'shared/error', model: f.object
      table
        tr
          th
            = f.label :name, 'ルーム名'
            .neccesary 必須
          td
            = f.text_field :name, placeholder: 'ルーム名を入力', class: 'input'
        tr
          th
            = f.label :introduction, 'ルーム紹介'
            .neccesary 必須
          td
            = f.text_area :introduction, placeholder: 'ルーム説明を入力', class: 'input_area'
        tr
          th
            = f.label :price, '料金'
            .neccesary 必須
          td
            = f.text_field :price, placeholder: '1日あたり料金を入力', class: 'input'
        tr
          th
            = f.label :adress, '住所'
            .neccesary 必須
          td
            = f.text_field :adress, placeholder: '住所を入力', class: 'input'
        tr
          th
            = f.label :photo, 'ルーム画像'
            .neccesary 必須
          td
            = f.file_field :photo
            = f.hidden_field :user_id, value:current_user.id
        tr
          th
            = f.submit '登録', class: 'button'

app/views/rooms/post.html.slim
= stylesheet_link_tag 'common','reservations_index'
.notice
    = flash[:notice]
.wrapper
  p 登録済みルーム一覧
  .rserved_room
    table
      thead
        tr
          th ルーム画像
          th ルーム名
          th ルーム紹介
          th 料金
          th 作成日
          th
      tbody
        -@rooms.each do |room|
          tr
            td.photo = link_to room_path(room.id)
              = image_tag room.photo.variant(resize_to_fill: [250,150])
            td.room_name = link_to "#{room.name}", room_path(room.id), id: "created_room_name"
            td = room.introduction
            td = room.price.to_s(:delimited, delimiter: ",") + "円"
            td = l room.created_at, format: :default
            td = link_to edit_room_path(room.id), class: "edit_room" do
              .edit
                p 編集
              = link_to room_path(room.id), method: :delete, data: {confirm: "ルームを削除してもよろしいですか？"}, class: "delete_room" do
                .delete
                  p 削除

app/views/rooms/search.html.slim
= stylesheet_link_tag 'common','index'
.result_sort
  .result
    p 検索結果：#{@results.count}件
  .sort
    = sort_link(@q, :price, "料金順")
.wrapper
  .search
    -@results.each do |room|
      .search_rooms
        = link_to room_path(room)
          .room_photo
            -if room.photo.attached?
              = image_tag room.photo.variant(resize_to_fill: [300,180]), class: 'photo'
          .room_information
            .room_name = room.name
            .room_adress = room.adress
            .room_price = room.price.to_s(:delimited, delimiter: ",") + "円"

app/views/rooms/show.html.slim
= stylesheet_link_tag 'common','show'
.show_room
  .show_photo_reservation
    -if @room.photo.attached?
      = image_tag @room.photo.variant(resize_to_fill: [700,400])
    .room_information
      .avatar
        = link_to admin_users_profile_path(@room.user.id)
          = image_tag @room.user.avatar.variant(resize_to_fill: [70,70]), id: "user_icon"
      .name_adress
        #name = @room.name
        br
        = @room.adress
    .introduction = @room.introduction
  .reservation_form
    .price = @room.price.to_s(:delimited, delimiter: ",") + "円 / 日"
    .form = form_with model: @reservation, local: true do |f|
      -if flash[:alert]
        .alert
          ul
            -flash[:alert].each do |alert|
              li = alert
      = f.label :start_day, "開始日"
      br
      = f.text_field :start_day, readonly: "readonly", class: "input_date"
      br
      = f.label :end_day, "終了日"
      br
      = f.text_field :end_day, readonly: "readonly", class: "input_date"
      br
      = f.label :number_of_people, "人数"
      br
      = f.number_field :number_of_people, min: 1, class: "input"
      br
      = f.hidden_field :room_id, value:@room.id
      -if current_user
        = f.hidden_field :user_id, value:current_user.id
        = f.submit "予約する", class: "button"
      -else
        = link_to login_path, id: "login" do
            .login
              | ログイン

app/views/shared/_error.slim
= stylesheet_link_tag 'error'
-if model.errors.any?
  .alert
    ul
      -model.errors.full_messages.each do |message|
        li = message

app/views/shared/_menu.slim
-if current_user
  = link_to "ルーム登録", new_room_path, id: "menu_text"
  br
  = link_to "予約済みルーム一覧", reservations_path, id: "menu_text"
  br
  = link_to "登録済みルーム一覧", rooms_post_path(current_user.id), id: "menu_text"
  br
  = link_to "設定", admin_user_path(current_user.id), id: "menu_text"
  br
  = link_to "ログアウト", logout_path, method: :delete, id: "menu_text"
  -if current_user.admin
  br
  = link_to "ユーザー一覧", admin_users_path, id: "menu_text"

app/views/shared/_searchform.slim
= search_form_for q, url: search_rooms_path do |f|
  = f.search_field :adress_cont, placeholder: "\uf3c5 エリア", class: "search_adress"
  = f.search_field :name_or_introduction_cont, placeholder: "\uf002 キーワード", class: "search_keyword"
  = f.search_field :price_gteq, placeholder: "\uf157 料金", class: "search_price"
  | ~
  = f.search_field :price_lteq, placeholder: "\uf157 料金", class: "search_price"
  = f.submit "検索", class: "search_room_button"